name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Require Sail
      run: composer require laravel/sail --dev
    - name: Install Sail
      run: php artisan sail:install --with=mysql,redis,meilisearch,mailhog,selenium
    - name: Sail Up
      run: ./vendor/bin/sail up
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Migrate
      run: php artisan migrate --force
    - name: Execute tests
      run: php artisan test
