name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8mb4'
        collation server: 'utf8mb4_general_ci'
        mysql version: '8.0'
        mysql database: 'ci_cd_practice'
        mysql root password: 'password'
    - name: Copy .env
      run: cp .env.example .env
    - name: Install Dependencies
      run: composer install --no-scripts
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Migrate
      run: php artisan migrate --force
    - name: Execute tests
      run: php artisan test
